"""
Jack The Shadow — Report Generation Tool

Generate structured penetration test reports from memory findings
and todo list. Outputs professional markdown or HTML.
"""

from __future__ import annotations

import glob as glob_mod
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any, ClassVar

from jack_the_shadow.tools.base import BaseTool
from jack_the_shadow.tools.builtin.memory import MEMORY_DIR, NOTES_FILE
from jack_the_shadow.tools.builtin.todo import TODOS_FILE
from jack_the_shadow.tools.helpers import result, truncate
from jack_the_shadow.utils.logger import get_logger

if TYPE_CHECKING:
    from jack_the_shadow.tools.executor import ToolExecutor

logger = get_logger("tools.report")

_VERSION = "0.3.0"

_CATEGORIES = ("recon", "credentials", "vulnerability", "exploit", "note")

_CATEGORY_LABELS = {
    "recon": "Reconnaissance",
    "credentials": "Credentials Discovered",
    "vulnerability": "Vulnerabilities",
    "exploit": "Exploits Used",
    "note": "Notes",
}

_TEMPLATE = """\
# Penetration Test Report

**Target:** [target description]
**Tester:** [your name]
**Date:** [date]
**Tool:** Jack The Shadow v{version}

---

## Executive Summary

Provide a high-level overview of the engagement, scope, and key findings.

## Methodology

- Reconnaissance and Information Gathering
- Vulnerability Assessment
- Exploitation
- Post-Exploitation
- Reporting

## Findings

### Reconnaissance

[List discovered hosts, services, open ports, DNS records, etc.]

### Vulnerabilities

[Describe each vulnerability with severity, affected component, and evidence.]

### Credentials Discovered

[List any credentials found during the engagement.]

### Exploits Used

[Describe exploitation techniques and their outcomes.]

### Notes

[Additional observations and notes.]

## Attack Plan Status

[Paste task checklist here.]

## Recommendations

Based on findings, the following remediation steps are recommended:

1. [Recommendation 1]
2. [Recommendation 2]
3. [Recommendation 3]

---
*Generated by Jack The Shadow*
""".format(version=_VERSION)


class ReportGenerateTool(BaseTool):
    name: ClassVar[str] = "report_generate"
    description: ClassVar[str] = (
        "Generate structured penetration test reports from memory findings "
        "and todo list. Outputs professional markdown reports with executive "
        "summary, methodology, findings, and recommendations."
    )
    risk_aware: ClassVar[bool] = False

    @classmethod
    def parameters_schema(cls) -> dict[str, Any]:
        return {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "enum": ["generate", "template", "export"],
                    "description": "Report action to perform.",
                },
                "title": {
                    "type": "string",
                    "description": (
                        'Report title (default: "Penetration Test Report").'
                    ),
                },
                "target": {
                    "type": "string",
                    "description": "Target description.",
                },
                "tester": {
                    "type": "string",
                    "description": 'Tester name (default: "Jack The Shadow").',
                },
                "format": {
                    "type": "string",
                    "enum": ["markdown", "html"],
                    "description": 'Output format (default: "markdown").',
                },
            },
            "required": ["action"],
        }


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _read_notes() -> str:
    """Read raw memory notes, return empty string if missing."""
    if not NOTES_FILE.exists():
        return ""
    try:
        return NOTES_FILE.read_text(encoding="utf-8")
    except OSError:
        return ""


def _read_todos() -> list[dict[str, Any]]:
    """Load the todo list."""
    if not TODOS_FILE.exists():
        return []
    try:
        data = json.loads(TODOS_FILE.read_text(encoding="utf-8"))
        return data if isinstance(data, list) else []
    except (json.JSONDecodeError, OSError):
        return []


def _parse_entries(notes: str) -> dict[str, list[str]]:
    """Split notes by ``## [category]`` headers into a category→entries map."""
    entries: dict[str, list[str]] = {c: [] for c in _CATEGORIES}
    current_cat: str | None = None
    buf: list[str] = []

    for line in notes.splitlines():
        match = re.match(r"^##\s*\[(\w+)\]", line)
        if match:
            # Flush previous buffer
            if current_cat and buf:
                entries.setdefault(current_cat, []).append("\n".join(buf).strip())
            current_cat = match.group(1).lower()
            if current_cat not in entries:
                current_cat = "note"
            buf = [line]
        else:
            buf.append(line)

    if current_cat and buf:
        entries.setdefault(current_cat, []).append("\n".join(buf).strip())

    return entries


def _format_entries(entries: list[str]) -> str:
    """Format a list of note entries into markdown."""
    if not entries:
        return "_No entries recorded._\n"
    return "\n\n".join(entries) + "\n"


def _format_todos(todos: list[dict[str, Any]]) -> str:
    """Render todos grouped by phase."""
    if not todos:
        return "_No tasks recorded._\n"

    by_phase: dict[str, list[dict[str, Any]]] = {}
    for t_item in todos:
        phase = t_item.get("phase", "unassigned") or "unassigned"
        by_phase.setdefault(phase, []).append(t_item)

    status_icons = {"pending": "[ ]", "in_progress": "[~]", "done": "[x]"}
    lines: list[str] = []
    for phase, items in sorted(by_phase.items()):
        lines.append(f"**{phase.replace('-', ' ').title()}**")
        for item in items:
            icon = status_icons.get(item.get("status", "pending"), "[ ]")
            lines.append(f"  {icon} #{item.get('id', '?')} — {item.get('task', '???')}")
        lines.append("")

    return "\n".join(lines)


def _auto_recommendations(entries: dict[str, list[str]]) -> str:
    """Generate basic recommendations based on finding categories."""
    recs: list[str] = []
    idx = 1

    if entries.get("vulnerability"):
        recs.append(
            f"{idx}. Remediate all identified vulnerabilities according to "
            "severity — prioritise Critical and High findings."
        )
        idx += 1

    if entries.get("credentials"):
        recs.append(
            f"{idx}. Rotate all discovered credentials immediately and enforce "
            "strong password policies with multi-factor authentication."
        )
        idx += 1

    if entries.get("exploit"):
        recs.append(
            f"{idx}. Patch or mitigate the software and configurations that "
            "allowed exploitation. Review access controls."
        )
        idx += 1

    if entries.get("recon"):
        recs.append(
            f"{idx}. Reduce the external attack surface by disabling unnecessary "
            "services and tightening firewall rules."
        )
        idx += 1

    recs.append(
        f"{idx}. Conduct a follow-up assessment to verify that all "
        "remediations have been applied effectively."
    )

    return "\n".join(recs)


def _generate_report(
    title: str,
    target: str,
    tester: str,
) -> str:
    """Build the full markdown report from memory + todos."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    notes_raw = _read_notes()
    entries = _parse_entries(notes_raw)
    todos = _read_todos()

    total = sum(len(v) for v in entries.values())
    vuln_count = len(entries.get("vulnerability", []))
    cred_count = len(entries.get("credentials", []))
    exploit_count = len(entries.get("exploit", []))

    sections: list[str] = []

    # Header
    sections.append(f"# {title}")
    sections.append("")
    sections.append(f"**Target:** {target}")
    sections.append(f"**Tester:** {tester}")
    sections.append(f"**Date:** {now}")
    sections.append(f"**Tool:** Jack The Shadow v{_VERSION}")
    sections.append("")
    sections.append("---")
    sections.append("")

    # Executive Summary
    sections.append("## Executive Summary")
    sections.append("")
    sections.append(
        "This report summarises the penetration testing engagement "
        "performed against the target environment. The assessment "
        "followed a structured methodology covering reconnaissance, "
        "vulnerability analysis, exploitation, and post-exploitation."
    )
    sections.append("")
    sections.append(
        f"Total findings: {total} | Vulnerabilities: {vuln_count} | "
        f"Credentials: {cred_count} | Exploits: {exploit_count}"
    )
    sections.append("")

    # Methodology
    sections.append("## Methodology")
    sections.append("")
    sections.append("- Reconnaissance and Information Gathering")
    sections.append("- Vulnerability Assessment")
    sections.append("- Exploitation")
    sections.append("- Post-Exploitation")
    sections.append("- Reporting")
    sections.append("")

    # Findings by category
    sections.append("## Findings")
    sections.append("")
    for cat in _CATEGORIES:
        sections.append(f"### {_CATEGORY_LABELS[cat]}")
        sections.append("")
        sections.append(_format_entries(entries.get(cat, [])))

    # Attack Plan Status
    sections.append("## Attack Plan Status")
    sections.append("")
    sections.append(_format_todos(todos))

    # Recommendations
    sections.append("## Recommendations")
    sections.append("")
    sections.append(
        "Based on findings, the following remediation steps are recommended:"
    )
    sections.append("")
    sections.append(_auto_recommendations(entries))
    sections.append("")

    # Footer
    sections.append("---")
    sections.append("*Generated by Jack The Shadow*")

    return "\n".join(sections)


def _md_to_html(md: str) -> str:
    """Minimal markdown-to-HTML conversion for report export."""
    lines = md.splitlines()
    html_lines: list[str] = [
        "<!DOCTYPE html>",
        "<html><head><meta charset='utf-8'>",
        "<title>Penetration Test Report</title>",
        "<style>body{font-family:sans-serif;max-width:900px;margin:auto;"
        "padding:2em}pre{background:#f4f4f4;padding:1em;overflow-x:auto}"
        "hr{border:none;border-top:1px solid #ccc}</style>",
        "</head><body>",
    ]

    in_pre = False
    for line in lines:
        if line.startswith("```"):
            if in_pre:
                html_lines.append("</pre>")
                in_pre = False
            else:
                html_lines.append("<pre>")
                in_pre = True
            continue

        if in_pre:
            html_lines.append(line)
            continue

        if line.startswith("### "):
            html_lines.append(f"<h3>{line[4:]}</h3>")
        elif line.startswith("## "):
            html_lines.append(f"<h2>{line[3:]}</h2>")
        elif line.startswith("# "):
            html_lines.append(f"<h1>{line[2:]}</h1>")
        elif line.startswith("---"):
            html_lines.append("<hr>")
        elif line.startswith("- "):
            html_lines.append(f"<li>{line[2:]}</li>")
        elif line.startswith("**") and line.endswith("**"):
            html_lines.append(f"<p><strong>{line[2:-2]}</strong></p>")
        elif line.strip() == "":
            html_lines.append("<br>")
        else:
            # Inline bold
            converted = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", line)
            html_lines.append(f"<p>{converted}</p>")

    if in_pre:
        html_lines.append("</pre>")

    html_lines.append("</body></html>")
    return "\n".join(html_lines)


def _find_last_report() -> Path | None:
    """Find the most recently generated report in MEMORY_DIR."""
    pattern = str(MEMORY_DIR / "report_*.md")
    files = sorted(glob_mod.glob(pattern))
    return Path(files[-1]) if files else None


# ---------------------------------------------------------------------------
# Handler
# ---------------------------------------------------------------------------

def handle_report_generate(
    executor: "ToolExecutor",
    action: str,
    title: str = "Penetration Test Report",
    target: str = "Not specified",
    tester: str = "Jack The Shadow",
    format: str = "markdown",
) -> dict[str, str]:
    logger.info("report_generate: action=%s format=%s", action, format)

    try:
        if action == "generate":
            report_md = _generate_report(title, target, tester)

            # Save to file
            MEMORY_DIR.mkdir(parents=True, exist_ok=True)
            ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
            report_path = MEMORY_DIR / f"report_{ts}.md"
            report_path.write_text(report_md, encoding="utf-8")

            logger.info("Report saved to %s", report_path)
            return result(
                "success",
                output=truncate(
                    f"Report saved to: {report_path}\n\n{report_md}"
                ),
            )

        elif action == "template":
            return result("success", output=_TEMPLATE)

        elif action == "export":
            last = _find_last_report()
            if last is None:
                return result(
                    "error",
                    message=(
                        "No report found. Use action='generate' first."
                    ),
                )

            md_content = last.read_text(encoding="utf-8")

            if format == "html":
                html_content = _md_to_html(md_content)
                html_path = last.with_suffix(".html")
                html_path.write_text(html_content, encoding="utf-8")
                logger.info("HTML report exported to %s", html_path)
                return result(
                    "success",
                    output=truncate(
                        f"HTML report saved to: {html_path}\n\n{html_content}"
                    ),
                )

            # markdown — just return existing content
            return result("success", output=truncate(md_content))

        else:
            return result("error", message=f"Unknown action: {action}")

    except Exception as exc:
        logger.error("report_generate failed: %s", exc)
        return result("error", message=f"Report generation failed: {exc}")
